- name: Create Prometheus Reader ClusterRoleBinding
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: prom-grafana-metrics-reader
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-monitoring-view
      subjects:
        - kind: ServiceAccount
          name: grafana-instance-sa
          namespace: grafana
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Create Prometheus Datasource
  kubernetes.core.k8s:
    definition:
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDatasource
      metadata:
        name: prometheus
        namespace: grafana
      spec:
        valuesFrom:
          - targetPath: "secureJsonData.httpHeaderValue1"
            valueFrom:
              secretKeyRef:
                name: "grafana-instance-sa-bearer"
                key: "BEARER_TOKEN"
        instanceSelector:
          matchLabels:
            dashboards: "grafana"
        datasource:
          name: "Prometheus"
          type: prometheus
          access: proxy
          url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
          jsonData:
            "tlsSkipVerify": true
            "httpHeaderName1": Authorization
          secureJsonData:
            "httpHeaderValue1": ${BEARER_TOKEN}
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed
